apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-petclinic
  namespace: springpetclinic
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: springpetclinic
    server: https://kubernetes.default.svc
  project: default
  source:
    path: spring-petclinic-eureka
    repoURL: https://github.com/pavelg-git/project_k8s_argocd_helm.git
    targetRevision: HEAD
